# Generated by Django 3.1.4 on 2020-12-03 12:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
