# Generated by Django 3.1.3 on 2020-12-07 09:20

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('hood_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hood_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('hood_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_name', to='hood.hood')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.hood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_join', to='hood.hood')),
                ('location', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hood_location_user', to='hood.hood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_join_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
