# Generated by Django 3.1.4 on 2020-12-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20201203_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='business',
            field=models.ManyToManyField(blank=True, related_name='hood_business', to='hood.Business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_in_hood', to='hood.neighbourhood'),
        ),
    ]
