# Generated by Django 3.1.4 on 2020-12-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20201203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=400)),
                ('description', tinymce.models.HTMLField()),
                ('hood_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_posts', to='hood.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood_post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
